#!/bin/bash
# Autor skryptu: Andrzej Szczepaniak
# Poprawki: Jakub 'unknow' Mrugalski


cp /etc/resolv.conf /etc/resolv.back



apk update
apk upgrade
apk add alpine-sdk musl-dev build-base libmnl-dev make wireguard-tools  git iptables  libqrencode libqrencode-dev xz 




if [ ! -e /dev/net/tun ]; then
    echo "Aby Wireguard działał poprawnie, musisz aktywować TUN/TAP na swoim serwerze";
    exit
fi


#20230223
#20191012
cd /tmp/ && wget https://git.zx2c4.com/wireguard-go/snapshot/wireguard-go-0.0.20230223.tar.xz && tar -xvf wireguard-go-0.0.20230223.tar.xz && rm wireguard-go-0.0.20230223.tar.xz && mv wireguard-go-0.0.20230223 wireguard-go
git -c http.sslVerify=false clone https://git.zx2c4.com/wireguard-tools /tmp/wireguard-tools

#go1.16.4.linux-amd64.tar.gz
#go1.21.0.linux-amd64.tar.gz
wget https://go.dev/dl/go1.21.0.linux-amd64.tar.gz -O /tmp/go1.21.0.linux-amd64.tar.gz

cd /tmp/ && tar -zxvf go1.21.0.linux-amd64.tar.gz
mv /tmp/go /usr/local
export GOROOT=/usr/local/go
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
ln -s /usr/local/go/bin/go /usr/bin/

cd /tmp/wireguard-tools/src/ || exit
make
make install

cd /tmp/wireguard-go/device/
rm /tmp/wireguard-go/device/queueconstants_default.go && wget https://fx.vc-mp.eu/shared/queueconstants_default.go
cd /tmp/wireguard-go && make
cp /tmp/wireguard-go/wireguard-go /usr/bin

wg genkey > /etc/wireguard/privatekey /et
wg genkey > /etc/wireguard/client-privatekey

chmod 600 /etc/wireguard/*privatekey*

cat /etc/wireguard/privatekey | wg pubkey > /etc/wireguard/publickey
cat /etc/wireguard/client-privatekey | wg pubkey > /etc/wireguard/client-publickey
srv=$(hostname)
privkey=$(cat /etc/wireguard/privatekey)
pubkey=$(cat /etc/wireguard/publickey)
cliprivkey=$(cat /etc/wireguard/client-privatekey)
clipubkey=$(cat /etc/wireguard/client-publickey)

# generator configa umieszczony na serwerze Mikrusa
curl -s -d "mode=wireguard-server&srv=$srv&privkey=$privkey&pubkey=$clipubkey" https://mikr.us/generator.php >/etc/wireguard/wg0.conf

echo -e "\n\n==============\n\nKonfiguracja klienta:\n\n"
curl -s -d "mode=wireguard-client&srv=$srv&privkey=$cliprivkey&pubkey=$pubkey" https://mikr.us/generator.php | tee /etc/wireguard/wg-client1.conf



rm -rf /tmp/wireguard-tools
rm -rf /tmp/wireguard-go
